"""Constants used throughout the application."""

EXCELLENT_ENGAGEMENT_THRESHOLD = 25.0
GOOD_ENGAGEMENT_THRESHOLD = 15.0
AVERAGE_ENGAGEMENT_THRESHOLD = 8.0
BELOW_AVERAGE_ENGAGEMENT_THRESHOLD = 3.0

HIGH_CONSISTENCY_THRESHOLD = 0.5
MEDIUM_CONSISTENCY_THRESHOLD = 1.0

HIGH_FREQUENCY_THRESHOLD = 3.0
MEDIUM_FREQUENCY_THRESHOLD = 1.0
LOW_FREQUENCY_THRESHOLD = 0.5

POST_ID_PARTS_COUNT = 2

EARLIEST_POST_ID = 2
DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

PERCENTILE_90 = 0.9
PERCENTILE_75 = 0.75

MIN_VALUES_FOR_GINI = 2
TOP_POSTS_PERCENTAGE = 10
MIN_WINDOWS_FOR_TREND = 2
MAX_TREND_WINDOWS = 12
TREND_GROWTH_THRESHOLD = 2.0
TREND_DECLINE_THRESHOLD = -2.0
